import * as d3 from 'd3'

const preptrator = d3.select('.preptrator')

d3.csv(require('../data/CaseNumber.csv'))
  .then(ready)
  .catch(err => console.log('Failed on', err))

function ready(datapoints) {
  const nest = d3
    .nest()
    .key(d => d.month)
    .entries(datapoints)

  const group = preptrator
    .selectAll('.group')
    .data(nest)
    .enter()
    .append('div')
    .attr('class', 'group')
    .attr('id', function(d) {
      const result = 'group' + d.key
      return result
    })

  // in each group add the appropriate number of blocks
  // group.append('text').text(d => d.key)

  const block = group
    .selectAll('.block')
    .data(d => d.values)
    .enter()
    .append('svg')
    .attr('class', 'block')
    .style('background-color', 'none')
    .attr('id', function(d) {
      const result = 'block' + d.preptrator
      return result
    })

  block
    .append('circle')
    .attr('cx', 31)
    .attr('cy', 31)
    .attr('r', 30)
    .attr('stroke', 'steelblue')
    .attr('stroke-width', 1.5)
    .attr('fill', 'steelblue')

  d3.select('#block0')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/0.png'))
    .attr('class', 'image0')

  d3.select('#block1')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/1.png'))
    .attr('class', 'image1')

  d3.select('#block2')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/2.png'))
    .attr('class', 'image2')

  d3.select('#block3')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/3.png'))
    .attr('class', 'image3')

  d3.select('#block4')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/4.png'))
    .attr('class', 'image4')

  d3.select('#block5')
    .append('image')
    .attr('x', 3)
    .attr('y', 3)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/5.png'))
    .attr('class', 'image5')

  d3.select('#block6')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/6.png'))
    .attr('class', 'image6')

  d3.select('#block7')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/7.png'))
    .attr('class', 'image7')

  d3.select('#block8')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/8.png'))
    .attr('class', 'image8')

  d3.select('#block9')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/9.png'))
    .attr('class', 'image9')

  d3.select('#block10')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/10.png'))
    .attr('class', 'image10')

  d3.select('#block11')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/11.png'))
    .attr('class', 'image11')

  d3.select('#block12')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/12.png'))
    .attr('class', 'image12')

  d3.select('#block13')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/13.png'))
    .attr('class', 'image13')

  d3.select('#block14')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/14.png'))
    .attr('class', 'image14')

  d3.select('#block15')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/15.png'))
    .attr('class', 'image15')

  d3.select('#block16')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/16.png'))
    .attr('class', 'image16')

  d3.select('#block17')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/17.png'))
    .attr('class', 'image17')

  d3.select('#block18')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/18.png'))
    .attr('class', 'image18')

  d3.select('#block19')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/19.png'))
    .attr('class', 'image19')

  d3.select('#block20')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/20.png'))
    .attr('class', 'image20')

  d3.select('#block21')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/21.png'))
    .attr('class', 'image21')

  d3.select('#block22')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/22.png'))
    .attr('class', 'image22')

  d3.select('#block23')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/23.png'))
    .attr('class', 'image23')

  d3.select('#block24')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/24.png'))
    .attr('class', 'image24')

  d3.select('#block25')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/25.png'))
    .attr('class', 'image25')

  d3.select('#block26')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/26.png'))
    .attr('class', 'image26')

  d3.select('#block27')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/27.png'))
    .attr('class', 'image27')

  d3.select('#block28')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/28.png'))
    .attr('class', 'image28')

  d3.select('#block29')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/29.png'))
    .attr('class', 'image29')

  d3.select('#block30')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/30.png'))
    .attr('class', 'image30')

  d3.select('#block31')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/31.png'))
    .attr('class', 'image31')

  d3.select('#block32')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/32.png'))
    .attr('class', 'image32')

  d3.select('#block33')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/33.png'))
    .attr('class', 'image33')

  d3.select('#block34')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/34.png'))
    .attr('class', 'image34')

  d3.select('#block35')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/35.png'))
    .attr('class', 'image35')

  d3.select('#block36')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/36.png'))
    .attr('class', 'image36')

  d3.select('#block37')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/37.png'))
    .attr('class', 'image37')

  d3.select('#block38')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/38.png'))
    .attr('class', 'image38')

  d3.select('#block39')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/39.png'))
    .attr('class', 'image39')

  d3.select('#block40')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/40.png'))
    .attr('class', 'image40')

  d3.select('#block41')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/41.png'))
    .attr('class', 'image41')

  d3.select('#block42')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/42.png'))
    .attr('class', 'image42')

  d3.select('#block43')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/43.png'))
    .attr('class', 'image43')

  d3.select('#block44')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/44.png'))
    .attr('class', 'image44')

  d3.select('#block45')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/45.png'))
    .attr('class', 'image45')

  d3.select('#block46')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/46.png'))
    .attr('class', 'image46')

  d3.select('#block47')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/47.png'))
    .attr('class', 'image47')

  d3.select('#block48')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/48.png'))
    .attr('class', 'image48')

  d3.select('#block49')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/49.png'))
    .attr('class', 'image49')

  d3.select('#block50')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/50.png'))
    .attr('class', 'image50')

  d3.select('#block51')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/51.png'))
    .attr('class', 'image51')

  d3.select('#block52')
    .append('image')
    .attr('x', 3)
    .attr('y', 3)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/52.png'))
    .attr('class', 'image52')

  d3.select('#block53')
    .append('image')
    .attr('x', 2.8)
    .attr('y', 2.8)
    .attr('width', 56)
    .attr('height', 56)
    .attr('xlink:href', require('../images/P-images/53.png'))
    .attr('class', 'image53')
}
